const SAFETY_CONTROL_AUTH_CONFIG = {
  mode: "mock",
  apiBaseUrl: "",
  endpoints: {
    requestWorkerCode: "/auth/worker/code",
    registerWorker: "/auth/worker/register",
    signInWorker: "/auth/worker/login",
    signInAdminWithGoogle: "/auth/admin/google",
    submitPayrollDocuments: "/worker/payroll-documents",
  },
  payrollDocumentRequiredWorkTypes: ["직접 고용"],
  workTypeOptions: ["직접 고용", "외부 고용"],
  demoAccount: {
    role: "worker",
    name: "박직접",
    phone: "010-1234-5678",
    code: "123456",
    password: "safety1234",
    workType: "직접 고용",
    team: "직접 고용 A팀",
    supervisor: "김안전 관리자",
  },
  demoAccounts: [
    {
      label: "직접 고용 계정",
      role: "worker",
      name: "박직접",
      phone: "010-1234-5678",
      code: "123456",
      password: "safety1234",
      workType: "직접 고용",
      team: "직접 고용 A팀",
      supervisor: "김안전 관리자",
    },
    {
      label: "외부 고용 계정",
      role: "worker",
      name: "이외부",
      phone: "010-2222-3333",
      code: "123456",
      password: "partner1234",
      workType: "외부 고용",
      team: "협력사 B팀",
      supervisor: "김안전 관리자",
    },
  ],
};
