const SAFETY_CONTROL_AUTH_CONFIG = {
  mode: "mock",
  apiBaseUrl: "",
  endpoints: {
    requestWorkerCode: "/auth/worker/code",
    registerWorker: "/auth/worker/register",
    signInWorker: "/auth/worker/login",
    signInAdminWithGoogle: "/auth/admin/google",
    submitPayrollDocuments: "/worker/payroll-documents",
  },
  payrollDocumentRequiredWorkTypes: ["직접 고용"],
  workTypeOptions: ["직접 고용", "외부 고용"],
  demoAccount: {
    role: "worker",
    name: "직접 고용 작업자",
    phone: "010-0000-0000",
    code: "123456",
    password: "safety1234",
    workType: "직접 고용",
    team: "직접 고용 A팀",
    supervisor: "관리자 A",
  },
  demoAccounts: [
    {
      label: "직접 고용 계정",
      role: "worker",
      name: "직접 고용 작업자",
      phone: "010-0000-0000",
      code: "123456",
      password: "safety1234",
      workType: "직접 고용",
      team: "직접 고용 A팀",
      supervisor: "관리자 A",
    },
    {
      label: "외부 고용 계정",
      role: "worker",
      name: "외부 고용 작업자",
      phone: "010-0000-0001",
      code: "123456",
      password: "partner1234",
      workType: "외부 고용",
      team: "협력사 B팀",
      supervisor: "관리자 A",
    },
  ],
};
