const dashboardWeather = buildDashboardWeather({
  ...mockKmaForecastResponse,
  baseDateTime: "2026-07-23T12:20:00+09:00",
  forecast: {
    ...mockKmaForecastResponse.forecast,
    temperature: 33,
    humidity: 63,
    rainProbability: 0,
    windSpeed: 6.8,
    skyCode: "DB01",
    uvIndex: "매우 높음",
  },
  correctionProfile: {
    ...mockKmaForecastResponse.correctionProfile,
    name: "워터밤 서울 무대 구역 보정",
    temperatureOffset: 1.5,
    windSpeedMultiplier: 1.15,
    rainProbabilityOffset: 0,
    humidityOffset: 2,
    reason: "무대 전면 개방 구역과 관객 밀집에 따른 체감 위험 보정값",
  },
});

const dashboardData = {
  event: {
    title: "워터밤 서울 D-1",
    date: "2026년 7월 23일 (목)",
    shortDate: "2026년 7월 23일",
    compactDate: "2026.07.23 (목)",
    location: "서울 잠실 보조경기장",
  },
  user: {
    name: "현장 근로자",
    role: "인프라팀",
    phone: "010-0000-0000",
    zone: "인프라팀",
    period: "2026.07.20 - 2026.07.27",
    status: "출근 확인",
  },
  dashboardRules: {
    status: "양호",
    items: [
      { icon: "◇", title: "안전고리 점검", checked: true },
      { icon: "♙", title: "안전모 착용", checked: true },
    ],
  },
  qr: {
    meal: {
      title: "식권 QR",
      label: "식권",
      remaining: 2,
      help: "운영 데스크에서 위 QR 코드를 스캔하세요",
    },
    water: {
      title: "생수 QR",
      label: "생수",
      remaining: 3,
      help: "워터 스테이션에서 위 QR 코드를 스캔하세요",
    },
  },
  weather: {
    ...dashboardWeather,
    workIndex: 45,
    workIndexLabel: "45% (제한적 가능)",
    alert: "자외선/풍속 주의: 15시 이후 실외 작업 중단 권고",
    metrics: [
      { icon: "≋", label: "풍속", value: "7.8 m/s", tone: "red" },
      { icon: "☁", label: "강수 확률", value: "0%", tone: "green" },
      { icon: "♨", label: "체감 온도", value: "34.5°C", tone: "orange" },
      { icon: "♢", label: "습도", value: "65%", tone: "orange" },
    ],
  },
  progress: {
    team: "내 팀: [리깅 A팀]",
    title: "무대 설치 현황",
    note: {
      schedule: "오늘 일정: 08:00 - 12:00",
      task: "주요 업무: 메인 트러스 인양 완료",
    },
    delay: {
      title: "[지연 알림]",
      body: "[음향팀] 세팅 지연으로 인해 [리깅 A팀] 작업 가능 시간이 14:00로 변경되었습니다.",
    },
    overall: 75,
    parts: [
      { label: "리깅", value: 100 },
      { label: "AV 연결", value: 80 },
      { label: "조명", value: 45 },
    ],
  },
  scheduleAlert: {
    title: "공정 지연 경고",
    body: "[음향팀] 메인 스피커 세팅 지연으로 인해 [리깅 A팀]의 후속 작업 가능 시간이 14:00로 변경되었습니다.",
  },
  teams: [
    {
      name: "리깅 A팀",
      task: "메인 무대 상부 트러스 리프팅",
      status: "지연",
      tone: "danger",
      originalTime: "11:00",
      changedTime: "14:00",
      progress: 15,
      action: "변경 이력 보기",
    },
    {
      name: "음향팀",
      task: "메인 L/R 스피커 어레이 세팅",
      status: "진행중",
      tone: "warning",
      startTime: "09:00",
      endTime: "13:30",
      progress: 65,
      action: "상세 정보",
    },
    {
      name: "조명팀",
      task: "스테이지 전면 무빙라이트 배선",
      status: "대기중",
      tone: "muted",
      startTime: "15:00",
      endTime: "18:00",
      progress: 0,
    },
  ],
  safetyNotice: {
    title: "폭염 경보 발령",
    body: "날씨가 매우 덥습니다. 작업 중 충분한 수분 섭취와 규칙적인 휴식을 반드시 지켜주시기 바랍니다.",
  },
  safetyBullets: [
    "현장 내 금연 및 화기 사용 엄금",
    "작업 전 개인 보호구 착용 상태 상호 점검",
    "음주 후 작업 현장 출입 절대 불가",
    "비상 탈출구 및 소화기 위치 사전 숙지",
  ],
  safetyChecklist: [
    {
      icon: "♙",
      title: "안전모 착용",
      description: "턱끈 체결 및 파손 여부 확인",
      checked: false,
    },
    {
      icon: "⚓",
      title: "안전 고리 체결",
      description: "고소 작업 시 이중 잠금 확인",
      checked: false,
    },
    {
      icon: "ϟ",
      title: "전기 설비 점검",
      description: "누전 차단기 및 전선 노출 확인",
      checked: false,
    },
  ],
  emergency: {
    name: "현장 매니저",
    phone: "010-0000-0000",
  },
  eventLinks: [
    { icon: "♧", label: "행사 맵 (Map)" },
    { icon: "◷", label: "타임테이블 (Timetable)" },
    { icon: "▣", label: "관객 FAQ" },
  ],
  documents: [
    { icon: "♙", label: "신분증 (ID Card)", status: "미제출", tone: "danger" },
    { icon: "▣", label: "통장 사본 (Bankbook Copy)", status: "제출 완료", tone: "info" },
  ],
  notifications: [
    {
      icon: "▲",
      title: "공정 지연 안내",
      body: "무대 B구역 급수 펌프 부하로 인해 특수효과 테스트 공정이 20분 지연되었습니다.",
      time: "10분 전",
      priority: "HIGH PRIORITY",
      tone: "danger",
    },
    {
      icon: "⬟",
      title: "안전 수칙 업데이트",
      body: "야외 구역 지면 미끄럼 방지 매트 설치에 따른 통행 주의 사항이 업데이트되었습니다.",
      time: "1시간 전",
      tone: "info",
    },
    {
      icon: "▣",
      title: "스케줄 변경 알림",
      body: "오후 2시 예정된 메인 스테이지 조명 리허설 시간이 30분 앞당겨졌습니다.",
      time: "3시간 전",
      tone: "muted",
    },
    {
      icon: "↶",
      title: "로그 기록 완료",
      body: "현장 안전 점검 일일 리포트가 시스템에 성공적으로 업로드되었습니다.",
      time: "어제",
      tone: "muted",
    },
  ],
};
